export const GET_SEARCH_ITEMS = 'GET_SEARCH_ITEMS'

export const DELETE_SEARCH_ITEMS = 'DELETE_SEARCH_ITEMS'

export const SET_LOCATION = 'SET_LOCATION'

export const SELECT_KEYWORD = 'SELECT_KEYWORD'

export const GET_SHOP_LIST = 'GET_SHOP_LIST'

export const GET_DIRECTION = 'GET_DIRECTION'

export const RESET_STATE_WITHOUT_SELECTED_SHOP = 'RESET_STATE_WITHOUT_SELECTED_SHOP'

export const SELECT_SHOP = 'SELECT_SHOP'

export const RESRT_STATE = 'RESRT_STATE'