export const SWITCH_COUPONS_CURRENT = 'SWITCH_COUPONS_CURRENT'

export const GET_ALL_COUPONS = 'GET_ALL_COUPONS'

export const SET_COUPONS_CURRENT_LIST = 'SET_COUPONS_CURRENT_LIST'

export const SET_ENABLE_LIST_NUMBER = 'SET_ENABLE_LIST_NUMBER'

export const SET_SELECTED_COUPONS = 'SET_SELECTED_COUPONS'
